[2024-05-12T15:56:34.473+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: data_etl_pipeline.store_data manual__2024-05-12T15:55:31.925392+00:00 [queued]>
[2024-05-12T15:56:34.550+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: data_etl_pipeline.store_data manual__2024-05-12T15:55:31.925392+00:00 [queued]>
[2024-05-12T15:56:34.568+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-05-12T15:56:34.569+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2024-05-12T15:56:34.570+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-05-12T15:56:34.780+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): store_data> on 2024-05-12 15:55:31.925392+00:00
[2024-05-12T15:56:34.815+0000] {standard_task_runner.py:55} INFO - Started process 3769 to run task
[2024-05-12T15:56:34.836+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_etl_pipeline', 'store_data', 'manual__2024-05-12T15:55:31.925392+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline.py', '--cfg-path', '/tmp/tmp2kanf7ww']
[2024-05-12T15:56:34.838+0000] {standard_task_runner.py:83} INFO - Job 23: Subtask store_data
[2024-05-12T15:56:35.934+0000] {task_command.py:376} INFO - Running <TaskInstance: data_etl_pipeline.store_data manual__2024-05-12T15:55:31.925392+00:00 [running]> on host 9137fdbbf522
[2024-05-12T15:56:36.713+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_etl_pipeline
AIRFLOW_CTX_TASK_ID=store_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-12T15:55:31.925392+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-12T15:55:31.925392+00:00
[2024-05-12T15:56:36.732+0000] {logging_mixin.py:120} INFO - Current Working Directory: /opt/***
[2024-05-12T15:56:36.733+0000] {logging_mixin.py:120} INFO - File to be version-controlled: data/extracted_data.json
[2024-05-12T15:56:36.734+0000] {logging_mixin.py:120} INFO - Error: The specified file data/extracted_data.json does not exist.
[2024-05-12T15:56:36.738+0000] {python.py:177} INFO - Done. Returned value was: None
[2024-05-12T15:56:36.815+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=data_etl_pipeline, task_id=store_data, execution_date=20240512T155531, start_date=20240512T155634, end_date=20240512T155636
[2024-05-12T15:56:36.980+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2024-05-12T15:56:37.170+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
